services:
  db:
    container_name: strapi_db
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi_user
      MYSQL_PASSWORD: strapi_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3307:3306'
    volumes:
      - strapi_db_data:/var/lib/mysql

  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db # Nome do servi√ßo definido acima
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_password
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./rbx-core:/opt/app/rbx-core
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1339:1339'
    depends_on:
      - db

volumes:
  strapi_db_data:
