version: '3.8'
services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: strapi-vendas:latest
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '127.0.0.1:1339:1339'
    networks:
      - db_default
    deploy:
      resources:
        limits:
          memory: 1024M
networks:
  db_default:
    external: true
